### ISSUE TITLE
correct_d bug

### ISSUE THREAD

**Issue by cynthiahsh** [psychmeta/psychmeta#121]
Hello. I'm trying to correct d values for measurement error using the correct_d command. However, I'm getting the following error: 

Error: Value supplied for r is not a correlation.
In addition: Warning message:
Some corrected correlations exceed 1 in absolute magnitude: Interpret results accordingly

Since I'm using correct_d and not correct_r, why am I getting this error? Here is what I input:

> correct_d (correction = "meas", d = (T3_d_r$d_Rstudio), ryy=(T3_d_r$ryy_w), ryy_type = "alpha", n1 = (T3_d_r$N_men), n2 = (T3_d_r$N_women))

Thank you!

**Comment by jadahlke** [comment]
Hello - psychometric corrections to d values are applied by transforming the d values to correlations, correcting them, and transforming them back into d values. The warning message that reads "Some corrected correlations exceed 1 in absolute magnitude: Interpret results accordingly" means that at least one of the corrections you're applying is implausible. After the d value is converted to a correlation, the reliability correction causes the corrected correlation to exceed 1.0 in magnitude, which makes it impossible to convert back to a d value. This could mean that the reliability coefficient you're using in the correction is not an appropriate index of reliability because it is too low to produce a statistically possible corrected value.

**Comment by cynthiahsh** [comment]
Hi Jeffrey,
Thank you for your quick response.
I will check into it.
Best,
Cynthia


[UTEP]
Dr. Cynthia Halliday, Ph.D.
Assistant Professor of Management

Woody L. Hunt College of Business
The University of Texas at El Paso
500 W. University Ave.
El Paso, TX 79968
Office: 915-747-7728
utep.edu<http://utep.edu/>

[Facebook]<https://www.facebook.com/UTEPMiners/>[Instagram]<https://www.instagram.com/utep_miners/>[Twitter]<https://twitter.com/utep>[YouTube]<https://www.youtube.com/user/UTEP>

**Comment by jadahlke** [comment]
No problem, Cynthia. If you're only correcting for measurement error, you might find it easier to apply equation 7 from this paper Brenton and I wrote about corrections: https://journals.sagepub.com/doi/pdf/10.1177/2515245919885611. In psychmeta, we rely on conversions between d and r to perform corrections within a unified framework, but corrections that only account for measurement error can be made without such a conversion.

**Comment by cynthiahsh** [comment]
Thank you, Jeffrey.


[UTEP]
Dr. Cynthia Halliday, Ph.D.
Assistant Professor of Management

Woody L. Hunt College of Business
The University of Texas at El Paso
500 W. University Ave.
El Paso, TX 79968
Office: 915-747-7728
utep.edu<http://utep.edu/>

[Facebook]<https://www.facebook.com/UTEPMiners/>[Instagram]<https://www.instagram.com/utep_miners/>[Twitter]<https://twitter.com/utep>[YouTube]<https://www.youtube.com/user/UTEP>
